create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'editor', 'viewer')),
  image text,
  is_active integer not null default 1 check (is_active in (0, 1)),
  last_login_at text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at text not null,
  created_at text not null
);

create table if not exists public.movie_backdrop_overrides (
  movie_id bigint primary key,
  selected_backdrop_path text not null,
  source text not null default 'tmdb',
  selected_by_user_id bigint references public.users(id) on delete set null,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at text not null,
  used_at text,
  created_at text not null
);

create index if not exists idx_sessions_token_hash on public.sessions(token_hash);
create index if not exists idx_sessions_user_id on public.sessions(user_id);
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_password_reset_tokens_hash on public.password_reset_tokens(token_hash);
create index if not exists idx_password_reset_tokens_user_id on public.password_reset_tokens(user_id);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.movie_backdrop_overrides enable row level security;
alter table public.password_reset_tokens enable row level security;
