create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'editor', 'viewer')),
  image text,
  is_active integer not null default 1 check (is_active in (0, 1)),
  last_login_at text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at text not null,
  created_at text not null
);

create table if not exists public.movie_backdrop_overrides (
  movie_id bigint primary key,
  selected_backdrop_path text not null,
  source text not null default 'tmdb',
  selected_by_user_id bigint references public.users(id) on delete set null,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at text not null,
  used_at text,
  created_at text not null
);

create table if not exists public.movie_trending_signals (
  movie_id bigint primary key,
  mention_count integer not null default 0,
  mentions_updated_at text,
  admin_order integer,
  admin_pinned integer not null default 0 check (admin_pinned in (0, 1)),
  updated_at text not null
);

create table if not exists public.validated_year_movies (
  year integer not null,
  movie_id bigint not null,
  payload text not null,
  created_at text not null,
  primary key (year, movie_id)
);

create table if not exists public.validated_year_freezes (
  year integer primary key,
  frozen_at text not null,
  movie_count integer not null
);

create table if not exists public.validated_year_progress (
  year integer not null,
  quarter integer not null,
  movie_count integer not null,
  completed_at text not null,
  primary key (year, quarter)
);

create table if not exists public.movie_hidden_videos (
  id bigint generated by default as identity primary key,
  movie_id bigint not null,
  youtube_key text not null,
  created_at text not null,
  unique (movie_id, youtube_key)
);

create index if not exists idx_movie_hidden_videos_movie_id on public.movie_hidden_videos(movie_id);

create table if not exists public.hidden_movies (
  movie_id bigint primary key,
  added_by_user_id bigint references public.users(id) on delete set null,
  created_at text not null
);

create table if not exists public.movie_release_overrides (
  movie_id bigint primary key,
  release_date text,
  aliases text,
  added_by_user_id bigint references public.users(id) on delete set null,
  updated_at text not null
);

create table if not exists public.movie_detail_overrides (
  movie_id bigint primary key,
  facts text,
  companies text,
  added_by_user_id bigint references public.users(id) on delete set null,
  updated_at text not null
);

create index if not exists idx_sessions_token_hash on public.sessions(token_hash);
create index if not exists idx_sessions_user_id on public.sessions(user_id);
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_password_reset_tokens_hash on public.password_reset_tokens(token_hash);
create index if not exists idx_password_reset_tokens_user_id on public.password_reset_tokens(user_id);
create index if not exists idx_trending_signals_admin_pinned on public.movie_trending_signals(admin_pinned);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.movie_backdrop_overrides enable row level security;
alter table public.password_reset_tokens enable row level security;
alter table public.movie_trending_signals enable row level security;
alter table public.validated_year_movies enable row level security;
alter table public.validated_year_freezes enable row level security;
alter table public.validated_year_progress enable row level security;
alter table public.movie_hidden_videos enable row level security;
alter table public.hidden_movies enable row level security;
alter table public.movie_release_overrides enable row level security;
alter table public.movie_detail_overrides enable row level security;

-- Video categories widened (lyrical, promo, interview, event, bts). movie_videos
-- was created outside this file; drop its old CHECK so new categories insert.
alter table if exists public.movie_videos drop constraint if exists movie_videos_category_check;

-- Community: user ratings & reviews, polls, quiz, admin-entered box office.
create table if not exists public.movie_user_ratings (
  user_id bigint not null references public.users(id) on delete cascade,
  movie_id bigint not null,
  rating integer check (rating is null or (rating >= 1 and rating <= 5)),
  watch_status text check (watch_status is null or watch_status in ('watched', 'want', 'no')),
  updated_at text not null,
  primary key (user_id, movie_id)
);

create index if not exists idx_movie_user_ratings_movie_id on public.movie_user_ratings(movie_id);

create table if not exists public.movie_user_reviews (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  movie_id bigint not null,
  movie_title text not null,
  author_name text not null,
  title text not null,
  body text not null,
  rating integer check (rating is null or (rating >= 1 and rating <= 5)),
  status text not null check (status in ('published', 'hidden')),
  created_at text not null,
  updated_at text not null,
  unique (user_id, movie_id)
);

create index if not exists idx_movie_user_reviews_movie_id on public.movie_user_reviews(movie_id);

create table if not exists public.polls (
  id bigint generated by default as identity primary key,
  question text not null,
  options text not null,
  movie_id bigint,
  movie_title text,
  is_active integer not null default 1 check (is_active in (0, 1)),
  created_by_user_id bigint references public.users(id) on delete set null,
  created_at text not null
);

create table if not exists public.poll_votes (
  poll_id bigint not null references public.polls(id) on delete cascade,
  voter_key text not null,
  option_index integer not null,
  created_at text not null,
  primary key (poll_id, voter_key)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options text not null,
  correct_index integer not null,
  category text not null default 'General',
  is_active integer not null default 1 check (is_active in (0, 1)),
  created_by_user_id bigint references public.users(id) on delete set null,
  created_at text not null
);

create table if not exists public.quiz_answers (
  question_id bigint not null references public.quiz_questions(id) on delete cascade,
  voter_key text not null,
  option_index integer not null,
  is_correct integer not null default 0 check (is_correct in (0, 1)),
  created_at text not null,
  primary key (question_id, voter_key)
);

create table if not exists public.movie_box_office (
  movie_id bigint primary key,
  movie_title text not null,
  poster_path text,
  release_date text,
  worldwide_gross text not null,
  note text,
  as_of text,
  added_by_user_id bigint references public.users(id) on delete set null,
  updated_at text not null
);

alter table public.movie_user_ratings enable row level security;
alter table public.movie_user_reviews enable row level security;
alter table public.polls enable row level security;
alter table public.poll_votes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.movie_box_office enable row level security;
